spring:
  application:
    name: financetracker
  datasource:
    url: jdbc:postgresql://localhost:5432/userregistration
    username:
    password:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080
